### PR TITLE
Export a list of the times taken to process each message.

### PR DESCRIPTION
**Pull request by ralphbean**
We can use this to graph more useful running stats in collectd. Notably, we
could graph the min, max, and average time taken to process. I want this in
particular for `datanommer`.  I have a hunch that the db `INSERT`
statements there get slower and slower over time until we go back and do a
`VACUUM ANALYZE;`, but I don't have data to back that up.  This should
let us see whether or not that's true.

### CODE REVIEW

**Comment by ralphbean** [comment]
To clarify, this is _expanding_ an API that moksha uses to expose stats about itself at runtime.  It periodically writes stats to a local unix socket about the the number of messages it has handled.  This should add new data to that JSON blob indicating how much time was taken for each message handled.

**Comment by nateyazdani** [comment]
Looks good! Definitely a useful change. My only question is, if the stats aren't pulled frequently enough (meaning `__json__()` not getting called, if I understand correctly), would the accumulation of stats in `Consumer._times` be problematic? I suppose it would take a very long time of neglected stats for this to happen and really depends on how that's managed in practice

**Comment by ralphbean** [comment]
It could be.  See [here](https://github.com/mokshaproject/moksha/blob/dev/moksha.hub/moksha/hub/monitoring.py#L28-L85) for the PollingProducer that flushes out the stats.  It is (supposed to be) called every 5 seconds.  In theory, we could accumulate too many time deltas in that list in that 5 second window and OOM ourselves, but in practice I don't think that will happen.

**Comment by nateyazdani** [comment]
Ah, I see. Agreed, I wouldn't reasonably expect five seconds to be long enough for that to be an issue. I was thinking on the order of months years, etc., if there wasn't anything actively taking care of those stats.

So that's a plus :+1: from me!

**Pull request merged**
