### PR TITLE
Feature/failover

### PR DESCRIPTION
**Pull request by ralphbean**

### CODE REVIEW

**Comment by ralphbean** [comment]
A thought -- if we reconnect to a different second broker.. do we have to re-send our subscriptions?

**Comment by ralphbean** [comment]
> if we reconnect to a different second broker.. do we have to re-send our subscriptions

After some research, I think the answer is "no".  So, this should be fine now.

**Comment by lmacken** [comment]
Looks good at a first glance, but why can't you just import the reactor once globally?

**Comment by ralphbean** [comment]
You're right; I guess we can do that.  For some reason I thought there would be a circular import, but its fine.

**Pull request merged**
