### PR TITLE
Python 3 compatibility for moksha.hub

### PR DESCRIPTION
**Pull request by frenzymadness**
Hello.

I am making moksha.hub module Python 3 compatible For now, all tests are passing with Python 2 and Python 3.
This PR is still WIP but reviews are welcome.

Will see what will happen in Travis with Python 3 enabled.

Have a nice day.
Lumír

### CODE REVIEW

**Comment by frenzymadness** [comment]
Tests failed so I reverted Python 3 related changes in .travis.yml file. But now, tests are failing again because Twisted needs at least Python 2.7.

Nevertheless, both problems mentioned above are not related to moksha.hub module. I'm attaching test results of moksha.hub for Python 2 and Python 3. (2.7.13 and 3.6.1).

From my point of view everything looks good and the changes could be merged and new version released.

Let me know, what do you think about it.

Have a nice day.
Lumír
[python2_test_results.txt](https://github.com/mokshaproject/moksha/files/1108011/python2_test_results.txt)
[python3_test_results.txt](https://github.com/mokshaproject/moksha/files/1108012/python3_test_results.txt)

**Comment by jeremycline** [comment]
It looks good from my perspective, thanks!

I proposed in https://github.com/fedora-infra/fedmsg/issues/418 that we drop Python 2.6 support in fedmsg after 0.19 - @ralphbean how do you feel about that and also dropping 2.6 here?

**Comment by ralphbean** [comment]
> how do you feel about that and also dropping 2.6 here?

:+1: :artificial_satellite:

**Comment by frenzymadness** [comment]
Perfect. Let's merge it and ship it in a new release, if possible.
If I can help you with anything (even Fedora package maintenance), let me know.

**Comment by ralphbean** [comment]
The releases are up on pypi now and I'm doing (non python3-repackaged) builds for rawhide.  @frenzymadness, or @jeremycline: do either of you want to take on the spec file changes?

**Comment by jeremycline** [comment]
If @frenzymadness is willing to do it, I definitely won't turn down the help 😃. Otherwise, I can do it when I make the spec file changes for fedmsg.

**Comment by frenzymadness** [comment]
Hello.
Sorry for the later reply, I was on vacation. I am gonna take a look at this and if everything will be ok, I could request rights for the python-moksha-hub package.

**Pull request merged**
