### PR TITLE
Add MQTT support for publishing

### PR DESCRIPTION
**Pull request by pabelanger**
Add the ability to publish message to a mqtt server.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
It looks like tests are broken?

**Comment by jeremycline** [comment]
Moksha's not really maintained and I think fedmsg needs to really lose it's dependency on it so I'd rather this just went into fedmsg. However, I'm curious why it is needed at all. What's the background on this?

**Comment by pabelanger** [comment]
Thanks fine with me, i started added it to fedmsg but opted for hear based on previous discussions.  We'd like to add fedmsg support into zuul-ci.org, but our backend of choice is mqtt for other services today.

**Comment by ralphbean** [comment]
- This looks reasonable to me.
- It doesn't look like `paho-mqtt` is packaged for Fedora, so we'll need to drop that dep there.  If you're willing to package it @pabelanger, we can keep this in place in the Fedora package.
- The tests work locally for me.  Odd - not sure why that feedcache dep is having a hard time.

@pabelanger, are you up for maintaining this extension long term?  If someone comes along with MQTT questions, I reckon I won't be able to answer them.

**Comment by ralphbean** [comment]
@pabelanger, can you rebase on the dev branch now that #55 is merged?

**Comment by ralphbean** [comment]
Ping @pabelanger.

**Comment by ralphbean** [comment]
OK.  I'm going to close this for now.  @pabelanger, if you get cycles to come back to this, rebase on `dev` and feel free to re-open.

**Pull request closed without merging**
